# Generated by Django 3.2.10 on 2022-07-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_auto_20220625_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='ownner',
            new_name='owner',
        ),
    ]
